apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: demo-voting-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app-pod1
      app: demo-voting-app1
  template:
    metadata:
      name: voting-app-pod1
      labels:
        name: voting-app-pod1
        app: demo-voting-app1

    spec:
      containers:
      - name: voting-app1
        image: shantanusohni/reactjs
        imagePullPolicy: Always
        ports:
        - containerPort: 80
